---
- hosts: local
  vars:
  - docroot: /var/www/awsomelabs.com/public
  tasks:
  - name: Add Nginx Repository
    apt_repository: repo='ppa:nginx/stable' state=present 
    register: ppastable 

  - name: Install Nginx
    apt: pkg=nginx state=installed update_cache=true
    when: ppastable|success
    register: nginxinstalled
    notify:
     - Start Nginx

  - name: Create Web Root
    when: nginxinstalled|success
    file: dest=/var/www/awsomelabs.com/public mode=755 state=directory owner=www-data group=www-data
    notify:
     - Reload Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started

   - name: Reload Nginx
     service: name=nginx state=reloaded
